apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g39sv0mvv-python
  janus-idp.io/tekton: g39sv0mvv-python
  backstage.io/kubernetes-id: g39sv0mvv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g39sv0mvv-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
